# Generated by Django 4.2.11 on 2025-08-20 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='申请状态')),
                ('reason', models.TextField(verbose_name='申请理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('target_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.role', verbose_name='目标角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '角色申请',
                'verbose_name_plural': '角色申请管理',
            },
        ),
    ]
