# Generated by Django 4.2.11 on 2025-08-19 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类管理',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='章节描述')),
                ('order', models.PositiveIntegerField(verbose_name='章节顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节管理',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课时标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='课时描述')),
                ('order', models.PositiveIntegerField(verbose_name='课时顺序')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='时长(秒)')),
                ('is_free', models.BooleanField(default=False, verbose_name='是否免费')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.chapter', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '课时',
                'verbose_name_plural': '课时管理',
                'ordering': ['chapter', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程标题')),
                ('description', models.TextField(verbose_name='课程描述')),
                ('cover_image', models.ImageField(upload_to='course_covers/', verbose_name='封面图片')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='课程价格')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('student_count', models.PositiveIntegerField(default=0, verbose_name='学习人数')),
                ('rating', models.FloatField(default=0.0, verbose_name='评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='课程分类')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
