# Generated by Django 4.2.11 on 2025-08-19 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='视频标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='视频描述')),
                ('file_url', models.CharField(max_length=255, verbose_name='视频文件URL')),
                ('thumbnail_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='缩略图URL')),
                ('duration', models.PositiveIntegerField(verbose_name='时长(秒)')),
                ('size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('format', models.CharField(blank=True, max_length=20, null=True, verbose_name='视频格式')),
                ('resolution', models.CharField(blank=True, max_length=20, null=True, verbose_name='分辨率')),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='uploading', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频管理',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_published',
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序顺序'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='是否免费'),
        ),
        migrations.AddField(
            model_name='course',
            name='cover_image_url',
            field=models.CharField(default='', max_length=255, verbose_name='封面图片URL'),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='beginner', max_length=20, verbose_name='难度'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='总时长(分钟)'),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='中文', max_length=50, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='course',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='评分人数'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('reviewing', '审核中'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='resource_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='资源URL'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('video', '视频'), ('document', '文档'), ('quiz', '测验')], default='video', max_length=20, verbose_name='课时类型'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.video', verbose_name='视频'),
        ),
    ]
