# Generated by Django 4.2.11 on 2025-08-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='答案内容')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='得分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='答题时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录管理',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='考试标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='考试描述')),
                ('duration', models.PositiveIntegerField(verbose_name='考试时长(分钟)')),
                ('total_score', models.PositiveIntegerField(default=100, verbose_name='总分')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='得分')),
                ('time_used', models.PositiveIntegerField(blank=True, null=True, verbose_name='用时(分钟)')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='是否提交')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '考试记录管理',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('tf', '判断题'), ('short', '简答题')], default='single', max_length=10, verbose_name='题目类型')),
                ('score', models.PositiveIntegerField(default=10, verbose_name='分值')),
                ('difficulty', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='难度(1-5)')),
                ('option_a', models.TextField(blank=True, null=True, verbose_name='选项A')),
                ('option_b', models.TextField(blank=True, null=True, verbose_name='选项B')),
                ('option_c', models.TextField(blank=True, null=True, verbose_name='选项C')),
                ('option_d', models.TextField(blank=True, null=True, verbose_name='选项D')),
                ('option_e', models.TextField(blank=True, null=True, verbose_name='选项E')),
                ('correct_answer', models.TextField(verbose_name='正确答案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题库管理',
            },
        ),
    ]
