# Generated by Django 4.2.11 on 2025-08-19 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_e',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否正确'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_score',
            field=models.PositiveIntegerField(default=60, verbose_name='及格分数'),
        ),
        migrations.AddField(
            model_name='examrecord',
            name='is_passed',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否通过'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='题目解析'),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='选项内容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('order', models.PositiveIntegerField(verbose_name='选项顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目选项',
                'verbose_name_plural': '题目选项管理',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='selected_answers', to='exams.questionoption', verbose_name='选择的选项'),
        ),
    ]
