# Generated by Django 4.2.11 on 2025-08-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='总学习人数')),
                ('completion_rate', models.FloatField(default=0.0, verbose_name='完成率(%)')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='总浏览量')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程统计',
                'verbose_name_plural': '课程统计管理',
            },
        ),
        migrations.CreateModel(
            name='LearningAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_learning_time', models.PositiveIntegerField(default=0, verbose_name='总学习时长(分钟)')),
                ('completed_lessons', models.PositiveIntegerField(default=0, verbose_name='已完成课时数')),
                ('average_score', models.FloatField(default=0.0, verbose_name='平均成绩')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学习分析',
                'verbose_name_plural': '学习分析管理',
            },
        ),
        migrations.CreateModel(
            name='TeachingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='总学生数')),
                ('average_completion_rate', models.FloatField(default=0.0, verbose_name='平均完成率(%)')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '教学分析',
                'verbose_name_plural': '教学分析管理',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('view_course', '查看课程'), ('start_learning', '开始学习'), ('complete_lesson', '完成课时'), ('submit_homework', '提交作业'), ('take_exam', '参加考试'), ('post_comment', '发表评论')], max_length=20, verbose_name='活动类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('device_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='活动时间')),
            ],
            options={
                'verbose_name': '用户活动',
                'verbose_name_plural': '用户活动管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
