# Generated by Django 4.2.11 on 2025-08-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作业标题')),
                ('description', models.TextField(verbose_name='作业描述')),
                ('total_score', models.PositiveIntegerField(default=100, verbose_name='总分')),
                ('deadline', models.DateTimeField(verbose_name='截止日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='提交内容')),
                ('file', models.FileField(blank=True, null=True, upload_to='homework_submissions/', verbose_name='提交文件')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='得分')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评语')),
                ('is_late', models.BooleanField(default=False, verbose_name='是否迟交')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='评分时间')),
            ],
            options={
                'verbose_name': '作业提交',
                'verbose_name_plural': '作业提交管理',
            },
        ),
    ]
