# Generated by Django 4.2.11 on 2025-08-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='allow_late_submission',
            field=models.BooleanField(default=True, verbose_name='允许迟交'),
        ),
        migrations.AddField(
            model_name='homework',
            name='difficulty',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='难度(1-5)'),
        ),
        migrations.AddField(
            model_name='homework',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
        migrations.AddField(
            model_name='homework',
            name='late_penalty',
            field=models.FloatField(default=0.1, verbose_name='迟交惩罚系数'),
        ),
        migrations.AddField(
            model_name='homework',
            name='passing_score',
            field=models.PositiveIntegerField(default=60, verbose_name='及格分数'),
        ),
        migrations.AddField(
            model_name='homework',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='homework',
            name='type',
            field=models.CharField(choices=[('programming', '编程作业'), ('essay', '论文作业'), ('report', '报告作业'), ('quiz', '测验作业'), ('other', '其他类型')], default='other', max_length=20, verbose_name='作业类型'),
        ),
        migrations.AddField(
            model_name='submission',
            name='feedback_file',
            field=models.FileField(blank=True, null=True, upload_to='homework_feedback/', verbose_name='反馈文件'),
        ),
        migrations.AddField(
            model_name='submission',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='submission',
            name='late_penalty_applied',
            field=models.FloatField(blank=True, null=True, verbose_name='已应用的迟交惩罚'),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('graded', '已评分'), ('rejected', '已退回')], default='draft', max_length=20, verbose_name='提交状态'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间'),
        ),
    ]
