# Generated by Django 4.2.11 on 2025-08-19 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_video_remove_course_cover_image_and_more'),
        ('learning', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='学习进度(秒)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='评分')),
                ('review', models.TextField(blank=True, null=True, verbose_name='评论')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='开始学习时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后学习时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lesson', verbose_name='课时')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学习进度',
                'verbose_name_plural': '学习进度管理',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': '收藏', 'verbose_name_plural': '收藏管理'},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'course')},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='courses.lesson', verbose_name='课时'),
        ),
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='笔记标题'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='courses.course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='视频时间点(秒)'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'lesson'), ('user', 'course')},
        ),
        migrations.DeleteModel(
            name='LearningRecord',
        ),
    ]
